version: "3"

services:
  web:
    restart: always
    build:
     context: ./
    container_name: nginx_reverse_proxy
    ports:
      - 80:80  
      - 443:443 
    volumes:
      - ./logs/:/var/log/nginx/:rw


